### ISSUE TITLE
Extract all board rendering logic

### ISSUE THREAD

**Issue by rjewson** [desca595/minesweeper#1]
https://github.com/desca595/minesweeper/blob/c90fc87b6d25db4bb4ee6cea297043eaa1390e33/src/Minesweeper/App.js#L124

Just like you did with Field, extract all the logic that renders the board to a separate component.  Dont put any game logic into this component.  Just pass it data (the board) and some functions to use a callbacks, and it returns a VDOM/JSX.  The rendering it with something like:

<Board data={this.state.board} onReveal={this.onReveal} onMark={this.onMark} />

**Comment by desca595** [comment]
done, pushed!
