### ISSUE TITLE
Make this a stateless functional component

### ISSUE THREAD

**Issue by rjewson** [desca595/minesweeper#2]
https://github.com/desca595/minesweeper/blob/c90fc87b6d25db4bb4ee6cea297043eaa1390e33/src/Minesweeper/Field.js#L3

You probably read about them:
https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc

Instead of a class extending React.Component, just have function, that returns VDOM e.g.

export const Field = (props) => <div>{props.something}</div>

Try and make all the components that render the board stateless like this.  There are number of advantages (easier to test, you keep the business logic out, they are more reusable etc)

**Comment by desca595** [comment]
done, pushed
